CREATE TABLE `manager` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '昵称',
  `mobile` VARCHAR(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '手机号',
  `status` VARCHAR(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '状态',
  `created_at` DATETIME DEFAULT NULL COMMENT '创建时间',
  `modified_at` DATETIME DEFAULT NULL COMMENT '更新时间',
  `deleted_at` DATETIME DEFAULT NULL COMMENT '作废时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPACT COMMENT='管理员';